shelves/urls.py
from django.urls import path
from shelves import views

app_name = 'shelves'

urlpatterns = [
    path('', views.index, name='index'),

    path('about/', views.about, name='about'),

    path('contact/', views.contact, name='contact'),

    path('media_collection/', views.list_media, name='list_media'),

    path('<str:media_type>/<slug:media_title_slug>/show_media', views.show_media, name='show_media'),

    path('add_media/', views.add_media, name='add_media'),

    path('<str:media_type>/<slug:media_title_slug>/add_details/', views.add_details, name='add_details'),

    path('<str:media_type>/<slug:media_title_slug>/add_post/', views.add_post, name='add_post'),

    path('register_profile/', views.register_profile, name='register_profile'),

    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),

    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),

    path('delete/<username>', views.delete_account, name='delete_account'),

    path('<username>/send_friend_request/', views.send_friend_request, name='send_friend_request'),

    path('<username>/accept_friend_request/', views.accept_friend_request, name='accept_friend_request'),

]

shelves_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from shelves import views
from registration.backends.simple.views import RegistrationView
from django.urls import reverse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('shelves:register_profile')


urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('shelves.urls'), name='index'),
        
        # New line below -- don't forget the slash after register!
        path('accounts/register/',
            MyRegistrationView.as_view(),
            name='registration_register'),
        
        path('accounts/', include('registration.backends.simple.urls')),
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shelves/forms.py
from django import forms
from shelves.models import Media, Book, Movie, Show, Song, Post, UserProfile
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator, int_list_validator


class MediaForm(forms.ModelForm):
    title = forms.CharField(max_length=Media.TITLE_MAX_LENGTH,
                                help_text="Please enter the media title")
    
    type = forms.CharField(help_text="Please select the type of media",
                            widget=forms.Select(choices=Media.TYPE_CHOICES))

    writer = forms.CharField(max_length=Media.WRITER_MAX_LENGTH,
                                help_text="Please enter the media author")

    language = forms.CharField(max_length=Media.LANG_MAX_LENGTH,
                                help_text="Please enter the media language")
    
    releaseDate = forms.DateField(help_text="Please the enter release date")

    class Meta:
        model = Media
        fields = ('title', 'writer', 'language', 'releaseDate', 'type', )


class BookForm(forms.ModelForm):
        isbn = forms.CharField(max_length=Book.ISBN_MAX_LENGTH, 
                               help_text="The ISBN number must be 13 digits long")
        
        class Meta:
            model = Book
            fields = ('isbn', )


class MovieForm(forms.ModelForm):
        duration = forms.DurationField(help_text="Please enter the duration of the movie (H:MM:SS)")
        
        class Meta:
            model = Movie
            fields = ('duration', )


class ShowForm(forms.ModelForm):
        episodes = forms.IntegerField(help_text="Please enter the number of episodes")
        seasons = forms.IntegerField(help_text="Please enter the number of seasons")
        
        class Meta:
            model = Show
            fields = ('episodes', 'seasons' )


class SongForm(forms.ModelForm):
        duration = forms.DurationField(help_text="Please enter the duration of the song (H:MM:SS)")
        
        class Meta:
            model = Song
            fields = ('duration', )


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=Post.TITLE_MAX_LENGTH,
                                    help_text="Enter the title of your post")
    
    rating = forms.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)],
                                    help_text="Provide a score between 0 and 10")
    
    comment = forms.CharField(widget=forms.Textarea, max_length=Post.COMM_MAX_LENGTH,
                                    help_text="Enter your comment")
    
    class Meta:
        model = Post
        fields = ['title', 'rating', 'comment',]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

shelves/views.py
from django.shortcuts import render
from shelves.models import Media, Book, Movie, Show, Song, Post, UserProfile, FriendRequest
from shelves.forms import MediaForm, BookForm, MovieForm, ShowForm, SongForm, PostForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User


def index(request):
    context_dict = {}

    try:
        media_list = Media.objects.order_by('-avgScore')[:10]
        post_list = Post.objects.order_by('-likes')[:10]

        context_dict['medias'] = media_list
        context_dict['posts'] = post_list
    
    except Media.DoesNotExist:
        context_dict['medias'] = None
        context_dict['posts'] = None

    response = render(request, 'shelves/index.html', context=context_dict)

    return response


def show_media(request, media_title_slug, media_type):
    context_dict = {}
    
    try:
        
        media = Media.objects.get(slug=media_title_slug, type=media_type)
        try:
            if request.user:
                user = UserProfile.objects.get_or_create(user=request.user)[0]
                user_friends = user.friends.all()
                posts = []
                if user_friends:
                    for friend in user_friends:
                        posts = posts + list(Post.objects.filter(media=media, user=friend.user))
                
                # Since user and media are linked uniquely in Post model
                posts = posts + list(Post.objects.filter(media=media, user=user.user))
        except:
            posts = None
        
        context_dict['media'] = media
        context_dict['posts'] = posts
    
    except Media.DoesNotExist:
        context_dict['media'] = None
        context_dict['posts'] = None

    return render(request, 'shelves/media.html', context=context_dict)


def list_media(request):
    media_collection = {}

    book_list = Book.objects.all()
    movie_list = Movie.objects.all()
    show_list = Show.objects.all()
    song_list = Song.objects.all()

    media_collection['books'] = book_list
    media_collection['movies'] = movie_list
    media_collection['shows'] = show_list
    media_collection['songs'] = song_list

    context_dict = {}
    context_dict['media_collection'] = media_collection
    
    response = render(request, 'shelves/list_media.html', context=context_dict)

    return response


@login_required
def add_media(request):
    media_form = MediaForm()

    if request.method == 'POST':
        media_form = MediaForm(request.POST)

        if media_form.is_valid():
            media = media_form.save(commit=False)
            media.user = request.user
            media.save()
            return redirect(reverse('shelves:add_details', kwargs={'media_title_slug': media.slug,
                                                                   'media_type': media.type}))
        else:
            print(media_form.errors)

    return render(request, 'shelves/add_media.html', {'form': media_form})


@login_required
def add_details(request, media_title_slug, media_type):
    try:
        media = Media.objects.get(slug=media_title_slug, type=media_type)
    except Media.DoesNotExist:
        media = None

    if media is None:
        return redirect(reverse('shelves:add_media'))
    
    if media.type == "book":
        type_form = BookForm
    elif media.type == 'movie':
        type_form = MovieForm
    elif media.type == 'show':
        type_form = ShowForm
    elif media.type == 'song':
        type_form = SongForm

    if request.method == 'POST':
        type_form = type_form(request.POST)

        if type_form.is_valid():
            type = type_form.save(commit=False)
            type.media = media
            type.save()

            return redirect(reverse('shelves:show_media',
                                    kwargs={'media_title_slug':
                                            media_title_slug,
                                            'media_type':
                                            media.type}))
        else:
            print(type_form.errors)

    context_dict = {'form': type_form, 'media': media}
    return render(request, 'shelves/add_details.html', context=context_dict)


@login_required
def add_post(request, media_title_slug, media_type):
    try:
        media = Media.objects.get(slug=media_title_slug, type=media_type)
    except Media.DoesNotExist:
        media = None

    if media is None:
        return redirect('/shelves/')

    post_form = PostForm()

    if request.method == 'POST':
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            if media:
                post = post_form.save(commit=False)
                post.media = media
                post.likes = 0
                post.user = request.user
                post.save()

                return redirect(reverse('shelves:show_media',
                                        kwargs={'media_title_slug':
                                                media_title_slug,
                                                'media_type':
                                                media.type}))
        else:
            print(post_form.errors)

    context_dict = {'form': post_form, 'media': media}
    return render(request, 'shelves/add_post.html', context=context_dict)


@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            
            return redirect(reverse('shelves:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'shelves/profile_registration.html', context_dict)


class ProfileView(View):
    def get_user_details(self, username, request):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'picture': user_profile.picture,})
        user_posts = Post.objects.filter(user = user.id)
        user_collection = Media.objects.filter(user = user.id)

        media_dict = {}
        media_dict['books'] = user_collection.filter(type='book')
        media_dict['movies'] = user_collection.filter(type='movie')
        media_dict['shows'] = user_collection.filter(type='show')
        media_dict['songs'] = user_collection.filter(type='song')

        friend_dict = {}
        if request.user == user:
            incoming_friend_requests = FriendRequest.objects.filter(receiver=user_profile.user)
            friend_dict['incoming_friend_requests'] = [request.sender for request in list(incoming_friend_requests)]
        
        else:
            friend_dict['selected_user_friends'] = user_profile.friends.all()
            friend_dict['self'] = UserProfile.objects.get(user=request.user)
            try:
                friend_dict['inbound_friend_request'] = FriendRequest.objects.get(receiver=request.user, sender=user_profile.user)
            except:
                friend_dict['inbound_friend_request'] = None
            try:
                friend_dict['outbound_friend_request'] = FriendRequest.objects.get(receiver=user_profile.user, sender=request.user)
            except:
                friend_dict['outbound_friend_request'] = None
        
        return (user, user_profile, form, user_posts, media_dict, friend_dict)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form, posts, media_collection, friend_dict) = self.get_user_details(username, request)
        except TypeError:
            return redirect(reverse('shelves:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form,
                        'posts': posts,
                        'media_collection': media_collection,
                        }
        
        context_dict.update(friend_dict)
        return render(request, 'shelves/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form,  posts, media_collection, friend_dict) = self.get_user_details(username, request)
        except TypeError:
            return redirect(reverse('shelves:index'))

        form = UserProfileForm(
            request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('shelves:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form,
                        'posts': posts,
                        'media_collection': media_collection,
                        }
        
        context_dict.update(friend_dict)
        return render(request, 'shelves/profile.html', context_dict)


@login_required
def delete_account(request, username):
    user = User.objects.get(username=username)
    if request.method == 'POST':
        user.delete()
        return redirect('/')

    return render(request, 'profile.html', {'user': user})


class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request,
                    'shelves/list_profiles.html',
                    {'user_profile_list': profiles})

templates/shelves/about.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
About
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">About Shelves</h1>
    </div>
</div>
<div class="container">
    Shelves is a website for you to share your interests in media.
</div>
{% endblock %}

templates/shelves/add_details.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add {{ media.type|title }} - Further Details
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add {{ media.type|title }} - Further Details</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="details_form" method="post"
            action="{% url 'shelves:add_details' media.type media.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Submit Details
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/shelves/add_media.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Media
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add Media</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="media_form" method="post" action="{% url 'shelves:add_media' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Media
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/shelves/add_post.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Post
{% endblock %}


{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add Post</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="post_form" method="post" action="{% url 'shelves:add_post' media.type media.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br>
            {{ field }}<br>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Post
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/shelves/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load shelves_template_tags %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/shelves.ico' %}">
    
    <!-- Title block -->
    <title>
        Shelves -
        {% block title_block %}
        {% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
            <a class="navbar-brand p-2" href="{% url 'shelves:index' %}">Shelves</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item "><a class="nav-link" href="{% url 'shelves:list_media' %}">Collection</a></li>
            <li class="nav-item "><a class="nav-link" href="{% url 'shelves:about' %}">About</a></li>
            <li class="nav-item "><a class="nav-link" href="{% url 'shelves:contact' %}">Contact</a></li>
            <form class="form-inline" id="search-form" method="get" action="">
                {% csrf_token %}
                <div class="form-inline">
                    <input class="form-control" type="search" size="50" name="query" value="{{ query }}"
                           id="query" placeholder="Enter name of media..." />
                </div>
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'shelves:add_media' %}">Add Media</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'shelves:list_profiles' %}">Members</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'shelves:profile' user.username %}">Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/">Logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
            </ul>
            </div>
        </nav>
    </header>

    <!-- Body block -->
    <div class="container-fluid">
        <div class="row">
            <main role="main" class="col-md-auto ml-sm-auto col-lg px-4">
                {% block body_block %}
                {% endblock %}
            </main>
        </div>
    </div>

    <!-- FOOTER -->
    <footer class="mt-auto">
        <hr style="width:95%">
        <div class="container">
            <div class="row">
                <div class="col-auto mr-auto">&copy; 2023 Shelves &middot; <a href="#">Privacy</a> &middot; <a
                        href="#">Terms</a></div>
                <p class="float-right"><a href="#">Back to top</a></p>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
</body>

</html>

templates/shelves/media.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% if media %}
{{ media.title }}
{% else %}
Unknown
{% endif %}
{% endblock %}

{% block body_block %}
{% if media %}
<div class="jumbotron p-4">
    <div class="container">
        <h1>{{ media.title }}</h1>
        <h5>made by {{ media.writer }}</h5>
    </div>
</div>
<div class="container">
    <div class="row">
        <ul type="bulletpoint">
            <li>Average Score: {{ media.avgScore }}</li>
            <li>Language: {{ media.language }}</li>
            <li>Release date: {{ media.releaseDate }}</li>
            {% if media.type|title == "Book" %}
            <li>ISBN: {{ media.book.isbn }}</li>
            {% endif %}
            {% if media.type|title == "Movie" %}
            <li>Duration: {{ media.movie.duration }}</li>
            {% endif %}
            {% if media.type|title == "Show" %}
            <li>Seasons: {{ media.show.seasons }}</li>
            <li>Episodes: {{ media.show.episodes }}</li>
            {% endif %}
            {% if media.type == "Song" %}
            <li>Duration: {{ media.song.duration }}</li>
            {% endif %}
            <!-- Need to enter code for cover image -->
        </ul>
    </div>
    <h5>Posts</h5>
    <div class="row mb-2">
        <div class="col-md-2 themed-grid-col">Title</div>
        <div class="col-md-2 themed-grid-col">Rating</div>
        <div class="col-md-2 themed-grid-col">Comment</div>
        <div class="col-md-2 themed-grid-col">Publish Date</div>
        <div class="col-md-2 themed-grid-col">Likes</div> <br>
        <div class="col-md-2 themed-grid-col">Posted by</div> <br>
        <hr style="width:95%">
        {% if posts %}
        {% for post in posts %}
        <div class="col-md-2 themed-grid-col">{{ post.title }}</div>
        <div class="col-md-2 themed-grid-col">{{ post.rating }} out of 10 stars</div>
        <div class="col-md-2 themed-grid-col">{{ post.comment }}</div>
        <div class="col-md-2 themed-grid-col">{{ post.publishDate }}</div>
        <div class="col-md-2 themed-grid-col">{{ post.likes }}</div>
        <div class="col-md-2 themed-grid-col">{{ post.user }}</div>
        <hr style="width:95%">
        {% endfor %}
        {% else %}
        <strong>No posts have been uploaded for this {{ media.type|lower }}.</strong>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <a href="{% url 'shelves:add_post' media.type media.slug %}"><Strong>Add Post?</Strong></a><br>
    {% else %}
    <p>You need to be logged in to add a post. <a href="/accounts/login/"> <Strong>Log in</Strong> </a> </p>
    {% endif %}

</div>
{% else %}
The media you specified is not available. Return to the <a
    href="{% url 'shelves:index' %}"><strong>Homepage</strong>.</a>
{% endif %}
{% endblock %}

templates/shelves/profile.html
{% extends 'shelves/base.html' %}
{% load staticfiles %}

{% block title_block %}
{{ selected_user.username }}'s Profile
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="150" height="150"
            alt="{{ selected_user.username }}'s profile image" />
        {% else %}
        <img src="{% static 'images/anonUser.png' %}" width="150" height="150"
            alt="{{ selected_user.username }}'s profile image" />
        {% endif %}
        <br>
        <div>
            <p>
                <strong>Join date: {{ user_profile.joinDate }}</strong>
            </p>
            {% if selected_user == user %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update" />
            </form>
            <br>
            <form action="{% url 'shelves:delete_account' selected_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete Account</button>
            </form>
            <br>
            {% elif inbound_friend_request %}
            <form action="{% url 'shelves:accept_friend_request' selected_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary btn-sm">Accept Friend Request</button>
            </form>
            {% elif outbound_friend_request %}
            <strong>Your friend request to {{ selected_user.username }} has been sent!</strong>
            {% elif self not in selected_user_friends %}
            <form action="{% url 'shelves:send_friend_request' selected_user.username %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary btn-sm">Send Friend Request</button>
            </form>
            {% else %}
            <strong>You and {{ selected_user.username }} are friends!</strong>
            {% endif %}
        </div>

        {% if selected_user == user %}
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Posts added: {{ post.count }}</h2>
                    <p class="card-text">
                    <ul class="list-group">
                        {% for post in posts %}
                        <li class="list-group-item">
                            <a href="{% url 'shelves:show_media' post.media.type post.media.slug%}">{{ post.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <strong>Friend Requests:</strong>
                    {% if incoming_friend_requests %}
                    <ul class="list-group">
                        {% for request in incoming_friend_requests %}
                        <li>
                            <a href="{% url 'shelves:profile' request.username %}">
                                {{ request.username }}
                            </a>
                            <form action="{% url 'shelves:accept_friend_request' request.username %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-secondary btn-sm">Accept Friend
                                    Request</button>
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    You don't have any incoming friend requests.
                    {% endif %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="panel-body">
            <div class="list-group">
                {% for type, objects in media_collection.items %}
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card mb-6">
                                <div class="card-body" id="{{ type }}">
                                    <h2>{{ type|title }} added:</h2>
                                    <p class="card-text">
                                        {% if objects %}
                                    <ul class="list-group">
                                        {% for object in objects %}
                                        <li class="list-group-item">
                                            <a href="{% url 'shelves:show_media' object.type object.slug %}">
                                                {{ object.title }}</a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    {% else %}
                                    <strong>{{ selected_user.username }} has not added {{ type }} to the
                                        website.</strong>
                                    {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}